---
title: "Data download"
author: "Anne van der Vliet"
date: "2025-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages
```{r}
#load needed packages
library(tidyverse)
library(knitr)
```


## Download dataset
```{r}
dropbox_url <- "https://www.dropbox.com/scl/fi/3jzhkicf953bsusjtu938/amz_uk_processed_data.csv?rlkey=ikvjt5kz4hy0tbdynrypb786n&st=6xb1y3g6&dl=1"
Amazon_UK <- read_csv(dropbox_url)
```

### Remove and rename columns
```{r warning=FALSE, include=FALSE}
#Drop columns
Amazon_UK <- Amazon_UK %>% select(-imgUrl) %>% select(-productURL) %>% select(-stars) %>% select (-reviews) %>% select(-isBestSeller)

#Rename columns
Amazon_UK <- Amazon_UK %>% rename(Product_ID = asin, Product_Name = title, Price = price, SalesLastMonth = boughtInLastMonth, Product_Category = categoryName)
```

## Data Description
For this project, a large dataset from Kaggle (https://www.kaggle.com/) was used, consisting of `r nrow(Amazon_UK)` Amazon products from the UK. The data was scraped in October 2023  and included the following variables:

```{r warning=FALSE, include=FALSE}
#give overview of variables and descriptions
table <- data.frame(`Variable` = c("Product_ID", "Product_Name", "Price", "SalesLastMonth", "Product_Category"), 
                    `Description` = c("Product ID from Amazon", 
                                      "Name of the product",
                                      "Current price of the product",
                                      "Number of products sold in the last month", "Product category"),
                    stringsAsFactors = FALSE
)

kable(table, format = "markdown")
```

## Data cleaning
```{r warning=FALSE}
#Prices of 0 removed as this meant no pricing information was available
Amazon_UK <- Amazon_UK %>% filter(Price >= 0.01)

#outlier detection per product category
quantile(Amazon_UK$Price, .01)
 
quantile(Amazon_UK$Price, .001)

Amazon_UK %>% group_by(Product_Category) %>% summarize(q001=quantile(Price, .001))
```

## Variable operationalization
```{r warning=FALSE}
#Price ending
Amazon_UK <- Amazon_UK %>%  mutate(HigherPrice = ceiling(Price))
Amazon_UK <- Amazon_UK %>%  mutate(BelowPrice = HigherPrice-Price)
Amazon_UK <- Amazon_UK %>%  mutate(PriceEnding = (1 - BelowPrice))
Amazon_UK$PriceEnding <- as.numeric(Amazon_UK$PriceEnding)

#Just-below vs. Round pricing (+ other)
Amazon_UK <- Amazon_UK %>%  mutate(Price_Strategy = case_when(
    PriceEnding > 0.9999 ~ "round",
    PriceEnding > 0.9899 & PriceEnding < 1.000 ~ "just-below",
    TRUE ~ "other"
  ))

#Price buckets
Amazon_UK = Amazon_UK %>% mutate(Price_Bucket = cut(Price, c(0,1,5,10,20,50,100, 500, 1000,10000000)))

#Top 10 categories
Categories = unique(Amazon_UK$Product_Category)
Categories = Amazon_UK %>% group_by(Product_Category) %>% summarize(Product_count = n()) %>% mutate(ranking = rank(-Product_count)) %>% mutate(top = ranking <= 10)
Categories_filtered = Categories %>% filter(top==T) %>% pull(Product_Category)
```
