---
title: "Data Analysis"
author: "Anne van der Vliet"
date: "2025-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, include=FALSE}
# Load needed packages
library(tidyverse)
library(knitr)
library(dplyr)
library(readr)
```

```{r}
# Load dataset based on "Data Download.Rmd"
Amazon_UK_Top10 <- read_csv("../../gen/data-preparation/data/AmazonDataTop10.csv")
```

## Descriptive statistics
```{r}
Amazon_UK_Top10 %>% 
  group_by(Product_Category) %>% 
  summarise(AmountofProducts = n(),
            PricedasJustBelow = sum(Price_Strategy == "just-below", na.rm = TRUE),
            PercentageJustBelow = round((PricedasJustBelow / AmountofProducts) * 100, 0),
            AveragePrice = round(mean(Price, na.rm = TRUE), 2), 
            MaxPrice = max(Price, na.rm = TRUE),
            MinPrice = min(Price, na.rm = TRUE),
            AverageReviewRating = round(mean(StarRating, na.rm = TRUE), 1))
```

## T-test main effect IV-DV
```{r}

```

## Regression MOD-DV
```{r}

```


## Explore possible control variables 
```{r}

```

## Main analysis
```{r}

```

